<?php

namespace ContainerV3JSfEi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0jUX5FGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0jUX5FG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0jUX5FG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.0jUX5FG.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.0jUX5FG": it needs an instance of "App\\Entity\\Client" but this type has been excluded in "config/services.yaml".'],
        ], [
            'client' => 'App\\Entity\\Client',
        ]);
    }
}
