<?php

namespace ContainerBLriSBz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.puJQK.a.App\Controller\InvoiceController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.puJQK.a.App\\Controller\\InvoiceController::delete()'] = ($container->privates['.service_locator.puJQK.a'] ?? $container->load('get_ServiceLocator_PuJQK_AService'))->withContext('App\\Controller\\InvoiceController::delete()', $container);
    }
}
