<?php

namespace ContainerBLriSBz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InvoiceController' shared autowired service.
     *
     * @return \App\Controller\InvoiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InvoiceController.php';
        include_once \dirname(__DIR__, 4).'/src/Interfaces/IInvoiceService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/invoiceServiceService.php';

        $container->services['App\\Controller\\InvoiceController'] = $instance = new \App\Controller\InvoiceController(new \App\Services\invoiceServiceService(($container->privates['App\\Repository\\InvoiceRepository'] ?? $container->load('getInvoiceRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\InvoiceController', $container));

        return $instance;
    }
}
