<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Invoice' => [parent::class, 'Invoice', null, 16],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'companyName' => [parent::class, 'companyName', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'managerFirstName' => [parent::class, 'managerFirstName', null, 16],
        "\0".parent::class."\0".'managerLastName' => [parent::class, 'managerLastName', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'Invoice' => [parent::class, 'Invoice', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'companyName' => [parent::class, 'companyName', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'managerFirstName' => [parent::class, 'managerFirstName', null, 16],
        'managerLastName' => [parent::class, 'managerLastName', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
