<?php

namespace ContainerBOkz1xM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6agy0ro.App\Controller\ClientController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.6agy0ro'] ?? $container->load('get_ServiceLocator_6agy0roService'));

        if (isset($container->privates['.service_locator.6agy0ro.App\\Controller\\ClientController::edit()'])) {
            return $container->privates['.service_locator.6agy0ro.App\\Controller\\ClientController::edit()'];
        }

        return $container->privates['.service_locator.6agy0ro.App\\Controller\\ClientController::edit()'] = $a->withContext('App\\Controller\\ClientController::edit()', $container);
    }
}
