<?php

namespace ContainerBOkz1xM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0jUX5FG.App\Entity\Client' shared service.
     *
     * @return \App\Entity\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0jUX5FG": it needs an instance of "App\\Entity\\Client" but this type has been excluded in "config/services.yaml".');
    }
}
