<?php

namespace ContainerBOkz1xM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MjtDUPf.App\Controller\InvoiceController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MjtDUPf.App\\Controller\\InvoiceController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'invoice' => ['privates', '.errored..service_locator.MjtDUPf.App\\Entity\\Invoice', NULL, 'Cannot autowire service ".service_locator.MjtDUPf": it needs an instance of "App\\Entity\\Invoice" but this type has been excluded in "config/services.yaml".'],
        ], [
            'invoice' => 'App\\Entity\\Invoice',
        ]))->withContext('App\\Controller\\InvoiceController::show()', $container);
    }
}
